# =============================================================================
# hyprland-config.nix — declarative Hyprland modular config
#
# Manages ~/.config/hypr/hyprland.conf plus ~/.config/hypr/modules/*.conf
# under home-manager. 12 user-pref files are baked in as plain text from
# /etc/nixos/home/hypr/modules/; 5 hardware-aware files are rendered by Nix
# from this module's options.
#
# Per-host overrides (monitors, disableDevices, etc.) live alongside this
# module under /etc/nixos/home/hosts/<hostname>.nix.
# =============================================================================
{ config, lib, pkgs, ... }:

let
  cfg = config.services.hyprlandConfig;

  envConfText = ''
    # Environment variables — generated by services.hyprlandConfig.
    env = XCURSOR_SIZE,${toString cfg.cursorSize}
    env = HYPRCURSOR_SIZE,${toString cfg.cursorSize}
    env = XCURSOR_THEME,${cfg.cursorTheme}
    env = GTK_THEME,${cfg.gtkTheme}
    env = GDK_BACKEND,wayland,x11,*
    env = CLUTTER_BACKEND,wayland
    env = SDL_VIDEODRIVER,wayland
    env = SSH_AUTH_SOCK,/run/user/${toString cfg.userId}/keyring/ssh
    env = GNOME_KEYRING_CONTROL,/run/user/${toString cfg.userId}/keyring
  '' + lib.concatMapStrings (e: "env = ${e}\n") cfg.extraEnv;

  envConfFile = pkgs.writeText "hyprland-Environment_Variables.conf" envConfText;

  devicesConfText = ''
    # Input devices and hardware blacklisting
    # Generated by services.hyprlandConfig — see kbLayout, sensitivity,
    # touchpad.*, and disableDevices options.

    input {
        kb_layout = ${cfg.kbLayout}
        numlock_by_default = true
        follow_mouse = 2
        sensitivity = ${toString cfg.sensitivity}
        repeat_rate = ${toString cfg.repeatRate}
        repeat_delay = ${toString cfg.repeatDelay}

        touchpad {
            natural_scroll = ${lib.boolToString cfg.touchpad.naturalScroll}
            tap-to-click = ${lib.boolToString cfg.touchpad.tapToClick}
            disable_while_typing = ${lib.boolToString cfg.touchpad.disableWhileTyping}
        }
    }
  '' + lib.concatMapStrings (name: ''

    device {
        name = ${name}
        enabled = false
    }
  '') cfg.disableDevices;

  devicesConfFile = pkgs.writeText "hyprland-Devices.conf" devicesConfText;

  monitorsConfText =
    let
      monitorLine = m:
        "monitor = ${m.name}, ${m.resolution}, ${m.position}, ${toString m.scale}";
      workspaceLines = m:
        map (ws: "workspace = ${toString ws}, monitor:${m.name}") m.workspaces;
    in ''
      # Monitor layout and workspace assignments
      # Generated by services.hyprlandConfig.monitors — override per host.
    '' + lib.concatStringsSep "\n" (map monitorLine cfg.monitors)
       + "\n\n"
       + lib.concatStringsSep "\n" (lib.flatten (map workspaceLines cfg.monitors))
       + "\n";

  monitorsConfFile = pkgs.writeText "hyprland-Monitors.conf" monitorsConfText;

  nvidiaConfText = if cfg.nvidia.enable then ''
    # NVIDIA on Wayland — env vars for the proprietary driver.
    env = LIBVA_DRIVER_NAME,nvidia
    env = __GLX_VENDOR_LIBRARY_NAME,nvidia
    env = WLR_NO_HARDWARE_CURSORS,1

    # Mute Hyprland's hardcoded "you're using an NVIDIA GPU" CHyprError
    # banner. No targeted knob exists; debug:suppress_errors is the only
    # mute and suppresses ALL CHyprError popups. Acceptable because
    # `hyprctl reload` still surfaces config-parse failures via exit code,
    # and nixos-rebuild gates activation on Nix eval + shellcheck.
    debug {
        suppress_errors = true
    }
  '' else ''
    # services.hyprlandConfig.nvidia.enable = false — no NVIDIA env vars emitted.
  '';

  nvidiaConfFile = pkgs.writeText "hyprland-Nvidia.conf" nvidiaConfText;

  nixConfFile = pkgs.writeText "hyprland-Nix.conf" ''
    # Nix / NixOS specific Hyprland settings (none needed)
  '';

  hyprlandConfText = ''
    # Main Hyprland configuration — generated by services.hyprlandConfig.
    # Per-machine overrides live in /etc/nixos/home/hosts/<hostname>.nix.
    source = ~/.config/hypr/modules/Environment_Variables.conf
    source = ~/.config/hypr/modules/Hypr_Ecosystem.conf
    source = ~/.config/hypr/modules/Devices.conf
    source = ~/.config/hypr/modules/Monitors.conf
    source = ~/.config/hypr/modules/Autostart.conf
    source = ~/.config/hypr/modules/Visual.conf
    source = ~/.config/hypr/modules/Animations.conf
    source = ~/.config/hypr/modules/Gestures.conf
    source = ~/.config/hypr/modules/Performance.conf
    source = ~/.config/hypr/modules/Binds.conf
    source = ~/.config/hypr/modules/Dispatchers.conf
    source = ~/.config/hypr/modules/Window_Rules.conf
    source = ~/.config/hypr/modules/Workspace_Rules.conf
    source = ~/.config/hypr/modules/Plugins.conf
    source = ~/.config/hypr/modules/Nix.conf
    source = ~/.config/hypr/modules/Nvidia.conf
    source = ~/.config/hypr/modules/Permissions.conf
  '' + lib.optionalString (config.services.voiceDictation.enable or false) ''
    source = ~/.config/hypr/modules/VoiceDictation.conf
  '';

  hyprlandConfFile = pkgs.writeText "hyprland.conf" hyprlandConfText;

  staticAutostart = builtins.readFile ./../hypr/modules/Autostart.conf;
  staticBinds     = builtins.readFile ./../hypr/modules/Binds.conf;
  staticRules     = builtins.readFile ./../hypr/modules/Window_Rules.conf;

  autostartConfFile = pkgs.writeText "hyprland-Autostart.conf" (
    staticAutostart
    + lib.optionalString (cfg.extraExecOnce != []) ''

      # --- extraExecOnce (from per-host override) ---
    ''
    + lib.concatMapStrings (cmd: "exec-once = ${cmd}\n") cfg.extraExecOnce
  );

  bindsConfFile = pkgs.writeText "hyprland-Binds.conf" (
    staticBinds
    + lib.optionalString (cfg.extraBinds != []) ''

      # --- extraBinds (from per-host override) ---
    ''
    + lib.concatMapStrings (b: "bind = ${b}\n") cfg.extraBinds
  );

  windowRulesConfFile = pkgs.writeText "hyprland-Window_Rules.conf" (
    staticRules
    + lib.optionalString (cfg.extraWindowRules != []) ''

      # --- extraWindowRules (from per-host override) ---
    ''
    + lib.concatMapStrings (r: "windowrulev2 = ${r}\n") cfg.extraWindowRules
  );
in
{
  options.services.hyprlandConfig = {
    enable = lib.mkEnableOption "declarative Hyprland config";

    mainMod = lib.mkOption {
      type = lib.types.str;
      default = "SUPER";
      description = "Modifier key referenced by \$mainMod in Binds.conf.";
    };

    userId = lib.mkOption {
      type = lib.types.int;
      default = 1000;
      description = "Numeric UID for /run/user/<UID>/keyring paths.";
    };

    cursorSize = lib.mkOption { type = lib.types.int; default = 24; };
    cursorTheme = lib.mkOption { type = lib.types.str; default = "Adwaita"; };
    gtkTheme = lib.mkOption { type = lib.types.str; default = "adw-gtk3-dark"; };

    kbLayout = lib.mkOption { type = lib.types.str; default = "us"; };
    sensitivity = lib.mkOption { type = lib.types.float; default = 0.5; };
    repeatRate = lib.mkOption { type = lib.types.int; default = 50; };
    repeatDelay = lib.mkOption { type = lib.types.int; default = 300; };

    touchpad = {
      naturalScroll      = lib.mkOption { type = lib.types.bool; default = false; };
      tapToClick         = lib.mkOption { type = lib.types.bool; default = true;  };
      disableWhileTyping = lib.mkOption { type = lib.types.bool; default = false; };
    };

    monitors = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          name       = lib.mkOption { type = lib.types.str; };
          resolution = lib.mkOption { type = lib.types.str; default = "preferred"; };
          position   = lib.mkOption { type = lib.types.str; default = "auto"; };
          scale      = lib.mkOption { type = lib.types.either lib.types.int lib.types.float; default = 1; };
          workspaces = lib.mkOption { type = lib.types.listOf lib.types.int; default = []; };
        };
      });
      default = [
        # Catch-all: empty name matches every output at preferred mode.
        { name = ""; resolution = "preferred"; position = "auto"; scale = 1; workspaces = []; }
      ];
    };

    disableDevices = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Hyprland device.name values to set enabled=false.";
    };

    nvidia.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Emit NVIDIA-on-Wayland env vars.";
    };

    extraExecOnce    = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
    extraBinds       = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
    extraWindowRules = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
    extraEnv         = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
  };

  config = lib.mkIf cfg.enable {

    # ---------------------------------------------------------------------
    # Static .conf files (universal user prefs — same on every host).
    # ---------------------------------------------------------------------
    xdg.configFile = {
      "hypr/modules/Animations.conf"     = { source = ./../hypr/modules/Animations.conf;     force = true; };
      "hypr/modules/Autostart.conf"      = { source = autostartConfFile;   force = true; };
      "hypr/modules/Binds.conf"          = { source = bindsConfFile;       force = true; };
      "hypr/modules/Dispatchers.conf"    = { source = ./../hypr/modules/Dispatchers.conf;    force = true; };
      "hypr/modules/Gestures.conf"       = { source = ./../hypr/modules/Gestures.conf;       force = true; };
      "hypr/modules/Hypr_Ecosystem.conf" = { source = ./../hypr/modules/Hypr_Ecosystem.conf; force = true; };
      "hypr/modules/Performance.conf"    = { source = ./../hypr/modules/Performance.conf;    force = true; };
      "hypr/modules/Permissions.conf"    = { source = ./../hypr/modules/Permissions.conf;    force = true; };
      "hypr/modules/Plugins.conf"        = { source = ./../hypr/modules/Plugins.conf;        force = true; };
      "hypr/modules/Visual.conf"         = { source = ./../hypr/modules/Visual.conf;         force = true; };
      "hypr/modules/Window_Rules.conf"   = { source = windowRulesConfFile; force = true; };
      "hypr/modules/Workspace_Rules.conf"= { source = ./../hypr/modules/Workspace_Rules.conf;force = true; };
      "hypr/modules/Environment_Variables.conf" = { source = envConfFile; force = true; };
      "hypr/modules/Devices.conf" = { source = devicesConfFile; force = true; };
      "hypr/modules/Monitors.conf" = { source = monitorsConfFile; force = true; };
      "hypr/modules/Nvidia.conf" = { source = nvidiaConfFile; force = true; };
      "hypr/modules/Nix.conf" = { source = nixConfFile; force = true; };
      "hypr/hyprland.conf" = { source = hyprlandConfFile; force = true; };
    };

    # ---------------------------------------------------------------------
    # Defensive permissions hook. If a prior install left ~/.config/hypr
    # root-owned (it does on max's current setup), this lets home-manager
    # write its symlinks. Idempotent — runs every activation.
    # ---------------------------------------------------------------------
    home.activation.fixHyprPerms = lib.hm.dag.entryBefore [ "linkGeneration" ] ''
      if [ -d "$HOME/.config/hypr" ] && [ ! -w "$HOME/.config/hypr" ]; then
        run echo "warning: $HOME/.config/hypr was not writable; this is being fixed via chmod, but the directory should be user-owned."
        run chmod -R u+rwX "$HOME/.config/hypr" 2>/dev/null || true
      fi
    '';
  };
}
