# Touchpad gestures
gestures {
   gesture = 3, horizontal, workspace
    workspace_swipe_distance = 500
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 120
   gesture = 3, down, close
}
