# Performance tweaks (miscellaneous section)
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    render_unfocused_fps = 0
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
}
